[package]
name = "libdb-sys"
version = "0.1.0"
authors = ["Karl Fischer <fishi0x01@gmail.com>"]

links = "db"
build = "build.rs"

[features]
default = []
v5_3 = []
v4_8 = []

[dependencies]

[build-dependencies]
bindgen = "0.51.1"
