[package]
name = "libdb-sys"
version = "0.1.0"
authors = ["Jesse Morgan <jesse@jesterpm.net>", "Karl Fischer <fishi0x01@gmail.com>"]

links = "db"
build = "build.rs"

[features]
v5_3 = []
v4_8 = []

[dependencies]
libc = "0.2.0"

[build-dependencies]
bindgen = "0.51.1"
