name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: sudo apt-get update && sudo apt-get install -y llvm-dev
      - name: Build v4.8
        run: cargo build --features v4_8 && cargo clean
      - name: Build v5.3
        run: cargo build --features v5_3 && cargo clean
